In [51]:
#importing libraries and loading dataset

import numpy as np
import pandas as pd

weather_data = pd.read_csv(r"C:\Users\Michal\Desktop\School\Bocconi\Courses\Business Analytics\ProbabilityAndStatistics-master\ProbabilityAndStatistics-master\Assignment_1\data\nycflights13\nycflights13_weather.csv", 
                           sep = ",", 
                           names=["origin","year","month","day","hour","temp","dewp","humid","wind_dir","wind_speed","wind_gust","precip","pressure","visib","time_hour"], 
                           skiprows = [0])

In [74]:
weather_data.head(10)

,origin,year,month,day,hour,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib,time_hour
0,EWR,2013,1,1,0,2.8,21.92,53.97,230.0,10.35702,11.918651,0.0,1013.9,10.0,2013-01-01 01:00:00
1,EWR,2013,1,1,1,2.8,21.92,53.97,230.0,13.80936,15.891535,0.0,1013.0,10.0,2013-01-01 02:00:00
2,EWR,2013,1,1,2,3.3,21.92,52.09,230.0,12.65858,14.567241,0.0,1012.6,10.0,2013-01-01 03:00:00
3,EWR,2013,1,1,3,3.3,23.00,54.51,230.0,13.80936,15.891535,0.0,1012.7,10.0,2013-01-01 04:00:00
4,EWR,2013,1,1,4,3.3,24.08,57.04,240.0,14.96014,17.215830,0.0,1012.8,10.0,2013-01-01 05:00:00
5,EWR,2013,1,1,6,3.9,26.06,59.37,270.0,10.35702,11.918651,0.0,1012.0,10.0,2013-01-01 07:00:00
6,EWR,2013,1,1,7,3.9,26.96,61.63,250.0,8.05546,9.270062,0.0,1012.3,10.0,2013-01-01 08:00:00
7,EWR,2013,1,1,8,3.9,28.04,64.43,240.0,11.50780,13.242946,0.0,1012.5,10.0,2013-01-01 09:00:00
8,EWR,2013,1,1,9,4.4,28.04,62.21,250.0,12.65858,14.567241,0.0,1012.2,10.0,2013-01-01 10:00:00
9,EWR,2013,1,1,10,3.9,28.04,64.43,260.0,12.65858,14.567241,0.0,1011.9,10.0,2013-01-01 11:00:00

In [53]:
#Converting temperatures into celsius

def tempConverter(temperature):
    temperature = (temperature - 32) * (5/9)
    return float(temperature)

weather_data["temp"] = weather_data["temp"].apply(tempConverter)

In [75]:
weather_data.head(20)

,origin,year,month,day,hour,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib,time_hour
0,EWR,2013,1,1,0,2.8,21.92,53.97,230.0,10.35702,11.918651,0.0,1013.9,10.0,2013-01-01 01:00:00
1,EWR,2013,1,1,1,2.8,21.92,53.97,230.0,13.80936,15.891535,0.0,1013.0,10.0,2013-01-01 02:00:00
2,EWR,2013,1,1,2,3.3,21.92,52.09,230.0,12.65858,14.567241,0.0,1012.6,10.0,2013-01-01 03:00:00
3,EWR,2013,1,1,3,3.3,23.00,54.51,230.0,13.80936,15.891535,0.0,1012.7,10.0,2013-01-01 04:00:00
4,EWR,2013,1,1,4,3.3,24.08,57.04,240.0,14.96014,17.215830,0.0,1012.8,10.0,2013-01-01 05:00:00
5,EWR,2013,1,1,6,3.9,26.06,59.37,270.0,10.35702,11.918651,0.0,1012.0,10.0,2013-01-01 07:00:00
6,EWR,2013,1,1,7,3.9,26.96,61.63,250.0,8.05546,9.270062,0.0,1012.3,10.0,2013-01-01 08:00:00
7,EWR,2013,1,1,8,3.9,28.04,64.43,240.0,11.50780,13.242946,0.0,1012.5,10.0,2013-01-01 09:00:00
8,EWR,2013,1,1,9,4.4,28.04,62.21,250.0,12.65858,14.567241,0.0,1012.2,10.0,2013-01-01 10:00:00
9,EWR,2013,1,1,10,3.9,28.04,64.43,260.0,12.65858,14.567241,0.0,1011.9,10.0,2013-01-01 11:00:00
10,EWR,2013,1,1,11,3.3,28.04,67.21,240.0,11.50780,13.242946,0.0,1012.4,10.0,2013-01-01 12:00:00
11,EWR,2013,1,1,12,3.9,28.04,64.43,240.0,14.96014,17.215830,0.0,1012.2,10.0,2013-01-01 13:00:00
12,EWR,2013,1,1,13,4.4,28.04,62.21,250.0,10.35702,11.918651,0.0,1012.2,10.0,2013-01-01 14:00:00
13,EWR,2013,1,1,14,4.4,28.04,62.21,260.0,14.96014,17.215830,0.0,1012.7,10.0,2013-01-01 15:00:00
14,EWR,2013,1,1,15,5.0,28.04,59.65,260.0,13.80936,15.891535,0.0,1012.4,10.0,2013-01-01 16:00:00
15,EWR,2013,1,1,16,5.0,26.96,57.06,260.0,14.96014,17.215830,0.0,1011.4,10.0,2013-01-01 17:00:00
16,EWR,2013,1,1,17,4.0,28.40,64.93,270.0,16.11092,18.540125,0.0,NaN,10.0,2013-01-01 18:00:00
17,EWR,2013,1,1,18,4.0,28.40,64.93,330.0,14.96014,17.215830,0.0,NaN,10.0,2013-01-01 19:00:00
18,EWR,2013,1,1,19,3.9,24.08,54.68,280.0,13.80936,15.891535,0.0,1010.8,10.0,2013-01-01 20:00:00
19,EWR,2013,1,1,20,3.3,24.08,57.04,290.0,9.20624,10.594357,0.0,1011.9,10.0,2013-01-01 21:00:00

In [76]:
#Computing daily mean temperatures for JFK

weather_data_JFK = weather_data[weather_data["origin"] == "JFK"].interpolate().groupby("day").mean()
weather_data_JFK["temp"].head(20)

day
1     13.620702
2     12.448958
3     11.945390
4     11.642857
5     12.748780
6     12.653125
7     12.827431
8     12.491667
9     12.884722
10    13.232292
11    13.775000
12    13.513889
13    11.507666
14    11.235764
15    12.149653
16    12.748432
17    12.940625
18    11.813542
19    12.653659
20    13.251389
Name: temp, dtype: float64

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.xlabel('Days')
plt.ylabel('Daily mean temperatures')
plt.title("Daily mean temperatures for January 2013 at JFK Airport")
plt.plot(weather_data_JFK["temp"])

In [77]:
#Days with greater mean temperature than in preceding day

better_days = weather_data_JFK[(weather_data_JFK.shift(periods=1)["temp"] - weather_data_JFK["temp"]) > 0]

better_days

,year,month,hour,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib
day,,,,,,,,,,,,
2,2013.0,6.500000,11.500000,12.448958,41.908125,65.023924,213.732639,10.716639,12.332494,0.000417,1015.023785,9.125868
3,2013.0,6.429078,11.709220,11.945390,40.844255,64.880638,225.319149,10.365182,11.928044,0.001028,1016.321927,9.119681
4,2013.0,6.484321,11.487805,11.642857,37.196794,57.105192,224.024390,11.608042,13.358303,0.000000,1018.836469,9.766551
6,2013.0,6.500000,11.500000,12.653125,43.498750,68.889757,168.072917,10.165223,11.697936,0.000729,1020.150347,8.600694
8,2013.0,6.500000,11.500000,12.491667,43.705625,69.295278,210.555556,12.638601,14.544249,0.010903,1018.865972,8.677951
12,2013.0,6.500000,11.500000,13.513889,45.475625,69.665625,183.680556,13.549635,15.592649,0.006285,1014.995269,8.395764
13,2013.0,6.494774,11.526132,11.507666,40.642509,66.366237,199.721254,11.391519,13.109132,0.002718,1015.861150,8.734321
14,2013.0,6.500000,11.500000,11.235764,38.213125,62.154375,228.107639,12.406847,14.277551,0.003194,1017.791840,8.921007
18,2013.0,6.500000,11.500000,11.813542,39.393750,61.702882,190.381944,10.696660,12.309502,0.001181,1019.588368,9.419653
21,2013.0,6.515679,11.522648,12.258885,40.063624,61.383206,205.871080,10.224700,11.766381,0.000627,1019.057491,9.477352
23,2013.0,6.489510,11.576923,11.930420,41.105105,65.700524,208.321678,12.912073,14.858956,0.003392,1015.722817,8.927413
24,2013.0,6.500000,11.500000,10.546181,36.030000,59.374063,256.423611,13.469720,15.500684,0.000868,1015.284583,9.320312
25,2013.0,6.500000,11.500000,9.105903,32.415625,55.760417,234.444444,12.654584,14.562642,0.000799,1019.272222,9.685764
28,2013.0,6.500000,11.500000,12.124653,41.583125,65.196146,194.982639,10.049346,11.564587,0.001215,1017.637153,9.541667

In [80]:
#5 warmest days

best_days = weather_data_JFK.sort_values(by = ["temp"], ascending = False).head(5)